### ISSUE TITLE
Blurry Image Zoom in iOS

### ISSUE THREAD

**Issue by Snowsoul** [rpearce/react-medium-image-zoom#101]
This issue is a:

- Bug report

## Expected behavior
I expected to see the zoomed in image to be sharp on a mobile device (iOS).

## Actual behavior
What actually happened was that the zoomed in image was really blurry.

![Image1](https://i.imgur.com/WxtmP85.jpg)
![Image2](https://i.imgur.com/YjpI5Wk.png)

## Steps to reproduce behavior

1. Go to https://rpearce.github.io/react-medium-image-zoom/ on a mobile device Safari or Chrome (iOS)
1. Tap an image and look at the sharpness of the image

I tried this on 3.0.5 locally and I get the same effect.

**Comment by rpearce** [comment]
@Snowsoul Thank you for reporting this! I'll check it out today.

**Comment by rpearce** [comment]
@Snowsoul thanks for this bug report! I added you to the [all contributors list](https://github.com/rpearce/react-medium-image-zoom#contributors) in the README.

The issue with this exists solely in the example. It did not have the mobile-friendly `<meta>` tags, and so when it was expanding the image to fit the viewport, it thought it was on a regular-sized webpage and was then scaling it by a factor of _2x_, which would naturally make any image blurry. The fix was to add the `<meta>` tag,

```html
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1">
```

to the `example/build/index.html` file.

Thanks again for the report!
