### ISSUE TITLE
Cursor: zoom-in when image is not zoomable

### ISSUE THREAD

**Issue by Tiendq** [rpearce/react-medium-image-zoom#105]
This issue is a:

- Bug report

## Expected behavior
I expected cursor is `default` pointer when image isn't zoomable e.g. when `shouldHandleZoom` returns `false`.

## Actual behavior
Cursor is always `zoom-in` by inline style.

## Steps to reproduce behavior
1. `shouldHandleZoom` returns `false`
2. Try to zoom an image

**Comment by rpearce** [comment]
@Tiendq Thank you for creating this issue. As `shouldHandleZoom` is a callback that is called _after_ a zoom trigger event occurs, the component cannot determine the hover state before such an action occurs.

Instead, since this is based on your logic, I would recommend that you use your own `className` or `style` property to determine the cursor. For example:
```js
<ImageZoom
  image={{
    src: '...',
    className: 'img',
    style: { cursor: 'default' }
  }}
/>
```
or
```js
<ImageZoom
  image={{
    src: '...',
    className: 'img img--disabled'
  }}
/>
```
where `.img--disabled` is
```css
.img--disabled {
  cursor: default;
}
```

**Comment by Tiendq** [comment]
Actually you can't use class `.img--disabled` since default inline style will override it. I don't want to add my own inline style to `image` too since cursor type is based on screen width (responsive design). I have used `!important`. Thanks.

```
.img--disabled {
  cursor: default !important;
}
```

**Comment by rpearce** [comment]
Yes, you are right: the `style` tag would indeed override the class. I'm glad you have something that works for your use case :+1:
