### ISSUE TITLE
Zooming and Unzooming with `Enter` Produces Errors

### ISSUE THREAD

**Issue by kendagriff** [rpearce/react-medium-image-zoom#106]
This issue is a: 

- Bug report

## Expected behavior

That the 'Enter' key works without throwing errors.

## Actual behavior

This might sound nit-picky, but it's happening with our users in production. If you open an image, and then sit and press `Enter` over and over (maybe 5 to 10 times?), invoking zoom and unzoom, eventually you can start throwing errors.

## Steps to reproduce behavior

1. Visit https://rpearce.github.io/react-medium-image-zoom/
2. Scroll to the first image.
3. Open Dev Tools.
3. Zoom the image.
4. Begin pressing `Enter` over and over.
5. Watch for errors.

![image](https://user-images.githubusercontent.com/110935/34618855-59cf0030-f1fd-11e7-8f0f-dd4c02e07a7b.png)

**Comment by rpearce** [comment]
@kendagriff Thank you for reporting this! This is a result of manually mounting and unmounting the zoom component. This makes me think about different way(s) this component library could work overall, so there's a "let's just fix the errors" vs. "let's structure it so that this couldn't happen" I'm currently going back and forth between.

I'll think on it some more and get back to you in a couple of days (it's Saturday here in NZ – hiking time!).

Thanks again.

**Comment by kendagriff** [comment]
@rpearce Thanks for getting back to me so quickly, have a great weekend!

**Comment by rpearce** [comment]
@kendagriff Just an FYI that I'll be looking at this in an hour or two

**Comment by rpearce** [comment]
@kendagriff Please upgrade to version `3.0.6`; the issue should be fixed!

**Comment by kendagriff** [comment]
Awesome, I think that fixed it! Thank you!

**Comment by rpearce** [comment]
@kendagriff I had forgotten to update the example in `gh-pages` with the latest and just did. Also glad that the update worked out for you!
