### ISSUE TITLE
Video support / Extensibility

### ISSUE THREAD

**Issue by mikkmartin** [rpearce/react-medium-image-zoom#116]
This issue is a: Feature request

## Video support
Hello.
Love the component, especially the elegant UX of it. Would like to know if there are plans or a possibility for video integration? As a better alternative to gif. https://help.imgur.com/hc/en-us/articles/208606616-What-is-GIFV-

I hacked together a simple version that replaces the image with a video tag as a proof of concept:
https://www.youtube.com/watch?v=sgAzI9YyxUI

If there are no plans for integrating this sort of functionality, can anyone point me in the right direction of extending this component?

Thanks in advance!

**Comment by rpearce** [comment]
@mikkmartin Thanks for reaching out and going to the trouble to make that proof-of-concept demo.

As you likely saw from the source, this library is built entirely around the concept of the `<img />` tag and what you can do with images. GIFV, WebM, MP4 and the like all deal with videos which have very different functionality and APIs to images.

I have thought about & considered in the past extracting the "zooming" part of this library to a more generic one that takes the dimensions of any object on the page and "zooms" it. Once the zoom animation was complete, it would call a callback that could then do anything; in your case, perhaps it would autoplay your video.

I'm happy to discuss here any thoughts you have on the subject. At present, I don't know of any library that does such a thing with the same method as this one (this one creates a separate DOM structure at the end of the `<body>` tag in order to avoid the pitfalls of CSS `tranform` and `overflow` usage).

**Comment by mikkmartin** [comment]
No problem, thanks for considering this.

The option of decoupling `<img>` + firing events on zoom/unzoom is exactly what i was looking for. This would solve my problem at least. Looked at a lot of alternative libraries. As you pointed out – none of which provided this functionality (especially with this good UX).

**Comment by rpearce** [comment]
@mikkmartin so to be clear:

Given an object on the screen with certain dimensions:
* expand that object to within X boundary (or zero) of the viewport
* maintain whatever its dimensions are
* have an overlay behind it of some type
* have all of the parameters customizable
* fire callbacks when certain events happen

What am I not thinking of?

**Comment by mikkmartin** [comment]
Looks good to me,

implementation wise – I was wondering about two things:
* What would the component api look like?
* How to pass thumbnail as optional "small" size of the zoomed object (eg. image thumbnail / smaller version of the image / video / object)?
Something that came to mind:
```jsx
<Zoom small={<ObjectSmall/>} onZoom={this.onZoom}>
  <Object/>
</Zoom>
```

**Comment by mikkmartin** [comment]
Yes, agree in video has a standard "full screen" button. Just as it's pretty standard to click on image thumbnail and have it open as a new page with displaying the image as well. That doesen't mean it can't be improved on – as medium did.

**Comment by rpearce** [comment]
@mikkmartin that's fair. As I don't have a current work use case for this and am getting married in a couple of weeks, I encourage you to use whatever you can from this library and others to help solve your use case.

**Comment by mikkmartin** [comment]
Ok, thanks anyway and congrats in a advance!

**Comment by oyeanuj** [comment]
@mikkmartin I'm curious if you ended up with a solution for your use-case here?
