### ISSUE TITLE
Handle scroll event using a container element

### ISSUE THREAD

**Issue by slorenzo** [rpearce/react-medium-image-zoom#136]
This issue is a:

- Bug report

## Expected behavior

To zoom out, use a container element when handling scroll event.

## Actual behavior

https://github.com/rpearce/react-medium-image-zoom/blob/master/src/EventsWrapper.js#L97

## Why?

This change allows use it with columns. So, If the dev wants to have a column with `overflow: auto` and a body with `overflow: hidden`, the zoom out  behavior will work.

Thanks for this amazing component!

**Comment by rpearce** [comment]
update: actually getting to this shortly. Thank you for your patience

**Comment by rpearce** [comment]
Sorry for delay. Looking now :eyes:

**Comment by rpearce** [comment]
Ah yes, this is a problem on some other projects I work on, as well. I had written it off as a "not sure what to do about this issue," but this may show some promise.

**Comment by slorenzo** [comment]
Yes, it's not a simple bug, anything you need, just let me know. I'm available to contribute.

**Comment by rpearce** [comment]
@slorenzo PRs are welcome for specifying a container everything should be attached to, but I also don't know how reasonably possible it is.

This is a far-reaching issue because the overlay, zoom image, listeners, etc., are all document/body based, and the reason is that we want the portal to be outside of any divs that may have `overflow` properties so that we can center it on the screen. If the overlay & zoomed image are constrained to a container, then the whole thing breaks down for it taking over the screen (it would only apply to the container). I believe the reason this bug exists is that the overlay and zoomed image are at the document/body level (and we have scroll listeners that will pick up scroll events at that top level), but if you have the zoom activated, then there's no way to scroll some content behind it in its own container (that I know of).

* * *

All that to say: "I don't know how to do this at the moment."

**Comment by rpearce** [comment]
Hi! We're not done with the rewrite, but we're keeping this issue in mind on this scroll feature issue here: https://github.com/rpearce/react-medium-image-zoom/issues/163
