### ISSUE TITLE
Allow customizing the z-index value of the container

### ISSUE THREAD

**Issue by navilan** [rpearce/react-medium-image-zoom#177]
Currently the container has a z-index value of 999.  It'd be great if the API accepted styles for the container or provided a way to override this value.

**Comment by rpearce** [comment]
@navilan We will keep that in mind for the next version! Thank you

**Comment by rpearce** [comment]
@navilan this should be resolved in the latest `react-medium-image-zoom@alpha` release.

I've added you to the contributors section in the README because of your idea here. Thanks!
<img width="379" alt="image" src="https://user-images.githubusercontent.com/592876/71793407-9be30300-3034-11ea-8822-8d93ed993b0b.png">

**Comment by navilan** [comment]
@rpearce - Thank you so much.
