### ISSUE TITLE
How to disable blue visited/focus border

### ISSUE THREAD

**Issue by 0x6e6562** [rpearce/react-medium-image-zoom#205]
This issue is a: 

- Question / support request

## Description

What's the most effective way to get rid of the blue visited/focus border around an image that occurs after you zoom an image back out?

Here's an example of having zoomed in and then out again:

<img width="156" alt="Screenshot 2020-01-06 09 52 52" src="https://user-images.githubusercontent.com/14088/71810620-afa95c00-306a-11ea-95e8-d006bd167138.png">

**Comment by rpearce** [comment]
This is an accessibility feature for keyboard (or other device) accessibility, but you should have the ability to control this in your application.

The blanket way to do so is something like
```css
*:focus {
  outline: none;
}
```
but that excludes a large number of people from being able to easily use an app, so here are some things to look at for you to decide how you want to handle it on your end:
* https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
* https://github.com/WICG/focus-visible
* https://css-tricks.com/keyboard-only-focus-styles/
* https://github.com/ten1seven/what-input

**Comment by 0x6e6562** [comment]
Many thanks for the heads up, I'll look into this. I was wondering why the default `react-medium-image-zoom` version 3.x doesn't display the same focus behavior as in version 4?

**Comment by rpearce** [comment]
That's because there were lines like https://github.com/rpearce/react-medium-image-zoom/blob/0044e710c17e03c0479c5cc432c7664fee049564/src/ImageZoom.js#L259-L261 that had all sorts of logic involved in focusing/not focusing depending on whether a mouse or keyboard was used. This was a contribution from a former colleague, for which I am still grateful.

However, hindsight has shown me that making an interactive element potentially inaccessible by trying to assume the consumer's intent is folly. Visible focus states are incredibly important to those with low visual acuity and those who use keyboards or other assistive devices, so I'd rather do what's "right" and allow the consumer of the component to figure out how they want to manage focus (or not).

**Comment by 0x6e6562** [comment]
Good point, thanks for the explanation.
