### ISSUE TITLE
Stop using css files therefore stop needing to import them.

### ISSUE THREAD

**Issue by dougg0k** [rpearce/react-medium-image-zoom#224]
Maybe use style objects instead, would make things more clean, since it's a small amount of styling.

What do you think?

**Comment by rpearce** [comment]
First, thank you for taking the time to think about this and open a PR.

What you have done was the scenario we had in [version 3.x](https://github.com/rpearce/react-medium-image-zoom/tree/v3.x), and I believe this to be an approach we might not want to take because of the following:
* it would be impossible to use pseudo-elements if we needed to
* overriding the library's styles would be a bit hairier, and you wouldn't be able to use the `style` attribute on an element to override the values and would have to use a nested object specifying what you want your changes to be
* how we want to approach vendor prefixing is not settled, so including a CSS file with vendor prefixes right now gives us the option of removing them and allowing consuming applications to determine what vendor prefixing to do. We can't do that with a style object
* bundling this in with a consuming application's CSS allows for that application's global styles to be able to take precedence; for example, `outline` styling.
* ...other reasons

At the moment, this is not a direction I think it best for the project to go in, but I thank you so very much for your effort here.

I will leave this and the PR open for a few days.

**Comment by dougg0k** [comment]
No, that's alright, make sense. Feel free to close it now if you want.

**Comment by dougg0k** [comment]
I wanted to let you know that here in a project using Gatsby + Styled-Components, but not passing Zoom through styled-components, your button still get a hashed css with partial class name that you are using in the library, so I'm not sure if it's because of Gatsby or styled-components. Here the class precedence didn't work as you can see in the screenshot, had to select the button with the aria-label.

[https://i.postimg.cc/BZymrg0y/ss.png](url)

**Comment by rpearce** [comment]
That image doesn't seem to be working

**Comment by dougg0k** [comment]
it is, try now.

**Comment by rpearce** [comment]
`styled-components`, `emotion`, `css-modules` and the like all inject their `<style>` tags dynamically at different places in the `<head>` (or even `<body>`). If that tag comes _before_ the `<style>` tag for normal CSS files/bundles, whatever comes last takes precedence. There are options for determining where styles get injected, but that differs from tool to tool.

That said, I am more than willing to have a conversation about the naming of classes, for this project dynamically generates the CSS class naming using CSS Modules, but that does mean that there's no reliable way for you to select them in your code. For example, `.Main_btn__3CiJa` is definitely going to be unique on your page, but if you're trying to override it, you're not going to have a good time. `RMIZ__btn` is a way to counteract that, but I'd need a good reason to change it from how it works right now.

**Comment by dougg0k** [comment]
#id doesn't seem to be changed by these libraries, it could be an option.

**Comment by rpearce** [comment]
Good point. Another option is `data-rmiz-btn`, which is selectable via `[data-rmiz-btn]`. I'll think on it.

**Comment by dougg0k** [comment]
Cool, sounds good.
