### ISSUE TITLE
Feature request: allow handleZoom to filter out ctrl-Click or cmd-Click 

### ISSUE THREAD

**Issue by rsaccon** [rpearce/react-medium-image-zoom#24]
When clicking on an image with `cmd` key pressed (or `ctrl` on windows), I am performing a different action than zooming. So I had to customize the handleZoom (I filtered out for all possible keyEvents):

```
  handleZoom(event) {
    if (!event.ctrlKey && !event.metaKey && !event.shiftKey && !event.altKey) {
      this.setState({ isZoomed: true })
    }
  }
```
Can we integrate this (or maybe an improved approach where one can provide an optional list which keys need to be filtered) ?

**Comment by rpearce** [comment]
@rsaccon I think that's something I can take a look at doing, though I'm not sure I can get to it today. I think passing in a data structure of things you want checked to disable the zoom is a reasonable request.

**Comment by rsaccon** [comment]
ok, great.

**Comment by rpearce** [comment]
@rsaccon How does this sound? Instead of passing down many different sorts of information, what about passing down a callback that receives the event and allows _you_ get to define what happens? For example (pseudo-code):
```js
static get defaultProps() {
  return {
    shouldZoom: (e) => true
  }
}

// ...

handleZoom(e) {
  if (this.props.shouldHandleZoom(e)) {
    this.setState({ isZoomed: true })
  }
}

// and then in your code

render() {
  <ImageZoom
    ...
    shouldHandleZoom={this.shouldZoom.bind(this)}
  />
}

shouldHandleZoom(e) {
  return !e.ctrlKey && !e.metaKey && !e.shiftKey && !e.altKey
}
```
I think something similar to this means that the library doesn't need to care about your implementation details and simply needs to respond to a boolean function call. How does that sound?

**Comment by rsaccon** [comment]
oh yes, that is much better !

**Comment by rpearce** [comment]
@rsaccon update to version `0.7.0` for the changes
