### ISSUE TITLE
"tslib.__spreadArrays is not a function" is thrown when the component is loaded:v4.3.0

### ISSUE THREAD

**Issue by nandhae** [rpearce/react-medium-image-zoom#249]
This issue is a:  Bug report

## Expected behavior
I expected to use the controlled zoom of 4.3.0 version by following the usage instructions in docs. (project react version:16.8.6)

## Actual behavior
What actually happened was...
As soon as i loaded the component with zoom component in it, it throws a control error saying "tslib.__spreadArrays is not a function"

doing a 'yarn add tslib' solves the problem. But i assume that it should not be needed. 

## Steps to reproduce behavior
1. Import the controlled component and styles as mentioned in the docs.
1. Cover any type of children with it and add it to a component.
1. Refresh the page

Thanks in advance for any directions/help on this.

**Comment by rpearce** [comment]
Thank you for your report! This is known and will be fixed in the next _major_ version (v5) already.

The problem here is that `tslib` is listed as a dev dependency and not a dependency (https://github.com/rpearce/react-medium-image-zoom/blob/master/package.json#L104).

I can patch v4 later today to fix this for now.

**Comment by rpearce** [comment]
@nandhae This should be fixed in version `4.3.1`. Please give it a try!

Do note that version `5` will be released soon!
