### ISSUE TITLE
React hydration issue

### ISSUE THREAD

**Issue by remorses** [rpearce/react-medium-image-zoom#338]
The following line computes a prop that will be different between server and client, generating the error `Warning: Prop `aria-labelledby` did not match. Server: "rmiz-modal-img-26f1" Client: "rmiz-modal-img-abe9"`

https://github.com/rpearce/react-medium-image-zoom/blob/df06121547fee3aa4618c61f35c756f6f9818140/source/Controlled.tsx#L93

React 18 introduced an `useId` hook that would be perfect for this use case, you can find the documentation here
https://reactjs.org/docs/hooks-reference.html#useid

**Comment by rpearce** [comment]
@remorses I am aware of that warning (it's not an error, right?), but what using `useId` means is that I'd have to drop the lower-bound of the React dependencies required to use the project. This wouldn't work for React 16.8, for example.

I'll keep this open so that I will explore another way to get that same `useId` concept in here and not have an issue on server vs client rendering.

**Comment by rpearce** [comment]
I am now wishing that I had upgraded the peer dependency on react to 18 and used `useId`. Doing so would be another major version change.

One option is to expose an `id` prop and have SSR users pass their own ID down. But that is a bummer and will lead people back to this issue over and over again.

Another way around this is to do a dynamic import like this: https://github.com/vercel/next.js/issues/12863#issuecomment-628660240, but that is a step backward and even more of a bummer.

I'm thinking about this 🤔

**Comment by rpearce** [comment]
Okay, I found a backwards-compatible way to do this with hooks, and then I remembered that I switched the main component here to a `class`, so this was an easy fix.

@remorses This should be fixed in version `5.0.1`. Thanks for your bug report here, and I've added that to your spot in the all contributors list in the README!

<img width="168" alt="imagen" src="https://user-images.githubusercontent.com/592876/182995076-599a88a2-c96d-4ac6-8773-a0d4eab5bfc6.png">
