### ISSUE TITLE
Neither `zoomMargin` nor `scrollableEl` seem to be working correctly

### ISSUE THREAD

**Issue by tom2strobl** [rpearce/react-medium-image-zoom#350]
## Issue Type

- [X] Bug report
- [ ] Feature request
- [X] Question / support request
- [ ] Other

## Description

I have found neither the `zoomMargin` nor `scrollableEl` props to work at all. Are there any examples and/or tests to verify expected behaviour?

Regarding `scrollableEl` I'm wondering how the scrollableElement is supposed to receive scroll events at all if the modal is layered above it – is there some special CSS within eg. `[data-rmiz-btn-unzoom]` that is expected to be implemented? Or are only 100% width/height divs supported?

Regarding `zoomMargin` not even a basic number like `zoomMargin={30}` seems to be doing anything, the zoomed modal versions of the image always reach the edge of the viewport for me.

I made a quick codesandbox to show that a zoomMargin of 100 definitely does not give 100 actual margin and afaik there's no way to properly implement scrollableEl: https://codesandbox.io/s/trusting-pare-kjg84f?file=/src/App.tsx

Note that the basic behaviour of the library works just fine.

**Comment by rpearce** [comment]
@tom2strobl I'll get on this this evening! ScrollableEl has always been a crap shoot where customization was needed, and I almost dropped it in v5.

zoomMargin should be working, and if it's not, I can fix that very quickly tonight. ScrollableEl might be a harder one to address.

**Comment by rpearce** [comment]
@tom2strobl Reckon we could drop `scrollableEl` since it's not working? I looked at using the `wheel` event just before shipping `v5`, and it worked very well when I played with it, but I was too busy with other aspects and forgot about it. The experience was that it swallowed the overall scroll for just a brief moment, then you kept scrolling down the page — kind of like a "scroll/swipe to close" sort of thing.

How does that feel?

**Comment by rpearce** [comment]
@tom2strobl Regarding the `zoomMargin`, it's definitely doing _something_, but it doesn't quite add up right. Check this out.

https://user-images.githubusercontent.com/592876/186300031-e2c4fb33-00d2-4669-bc71-042cff74e186.mp4

**Comment by rpearce** [comment]
@tom2strobl I'm really liking your feedback here. Thank you for it!

Regarding "staying close to Medium", that was the case for years, but not any more. For example, this solution should be way more accessible (I do a lot of a11y work) -- especially when since v5.1 will include the ability to add custom content to the model like captions. Also, Medium's image zoom hasn't worked for me in Firefox for some time.

I rebranded the library to be a "Medium.com-style" library, so no more worries there.

* * *

1. I'll try to fix the zoomMargin math. I'd like to do this first and ship a patch fix at the v5.0.x version level. 
2. I'll look at removing the broken scrollableEl and get some wheel events going. If this goes well, I'll include it in v5.1.0 along with the custom modal content feature.

**Comment by rpearce** [comment]
I didn't realize how burned out on this I was getting until your last comment here. 💜 

I'll see what I can do this weekend.

**Comment by rpearce** [comment]
Late night update: I've not fixed the `zoomMargin` yet, but the `scrollableEl` has been removed and replaced with the `wheel` event as of https://github.com/rpearce/react-medium-image-zoom/pull/362.

That is getting merged into the `v5-dev` branch, and once I do some more testing, I'll release `v5.1.0` with the following changelog (in case you're interested):

## [5.1.0] - 2022-10-06

### Added

* Ability to customize the zoom modal content via `<ZoomContent>` (issue #332)
* Re-added `wrapElement` prop to API (issue #356)
* Added a11y support for `prefers-reduced-motion: reduce` (issue #359)

### Changed

* Now rendering `<dialog>` in a portal because of #356. This will affect the
  probably non-existent portion of people using CSS like `.my-class
  [data-rmiz] {}`

### Fixed

* Now using the `wheel` event instead of `scroll` to detect trying to leave the
  modal (issue #350)
* Fixed mobile scrolling experience (related to issue #350)

### Removed

* Removed the broken `scrollableEl` that has arguably not ever worked (issue #350)

**Comment by tom2strobl** [comment]
haha I was actually one of the non-existent portion of people using the `[data-rmiz] {}` css selector stuff on module level, but no biggie, just moved the selector out of the module to a global selector. portals are almost always the cleaner option for stuff like this anyway.

Your `wheel` changes aren't yet on npms `5.1.0-beta.4`, right? Let me know once you throw it on a beta branch on npm and I'm happy to test if it works for me

**Comment by rpearce** [comment]
@tom2strobl omg I'm so sorry. I could also accept a CSS class name to pass to the portal in order to differentiate one dialog from another (leaning this way).

The wheel-based code isn't yet solid because of body scrolling issues I'm still working through -- mostly Safari on macOS and iOS, but it rears its head in some way across the boards.

I will :100: drop a note here when it's out on beta. I really want to get these right, and I get about an hour per late night every few nights to try to power through things.

**Comment by rpearce** [comment]
Update from tonight!

* _Should_ have the wheel events and body locking issues sorted (https://github.com/rpearce/react-medium-image-zoom/commit/1dbb392b4e7b65c40256ccbd6c8c726755256e30)
* Introduced a `classDialog` prop to provide a class that should be used on a given `<dialog>` on zoom (https://github.com/rpearce/react-medium-image-zoom/commit/cb969f1149e65b3fac94e05e9005efbb94ad818a)
* Published the latest [`v5-dev`](https://github.com/rpearce/react-medium-image-zoom/compare/main...v5-dev) branch updates as `react-medium-image-zoom@5.1.0-beta.5`

**Comment by tom2strobl** [comment]
@rpearce looks pretty good to me!
FYI you `preventDefault` in `ControlledBase.handleWheel`, but register the event handler as passive, which is [impossible](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener?retiredLocale=de#:~:text=If%20a%20passive%20listener%20does%20call%20preventDefault()%2C%20the%20user%20agent%20will%20do%20nothing%20other%20than%20generate%20a%20console%20warning.). Thats also why the console logs `Unable to preventDefault inside passive event listener invocation`.

**Comment by rpearce** [comment]
@tom2strobl beta7 should have that removed as of last night!

**Comment by rpearce** [comment]
The `zoomMargin` bug still needs to be figured out, so this issue will remain open, but `scrollableEl` has been removed, and there are a bunch of other improvements / additions in `v5.1.0` that is now released.

I also added you to the All Contributors section in the README for your contributions. Thank you for your time 💜

**Comment by rpearce** [comment]
@tom2strobl I may have figured it out: https://github.com/rpearce/react-medium-image-zoom/pull/368

Could it possibly be this easy?!
<img width="1087" alt="github diff" src="https://user-images.githubusercontent.com/592876/195494343-ef95d19d-8d8a-43dd-b65f-189750dfeff2.png">
