### ISSUE TITLE
Feature request/tabIndex prop

### ISSUE THREAD

**Issue by SaadAhmadSaddiqui** [rpearce/react-medium-image-zoom#364]
## Issue Type

- [ ] Bug report
- [x] Feature request
- [ ] Question / support request
- [ ] Other

## Description
Tab index prop that allows to pass custom tab index number and be able to zoom in with space bar or enter depending on whether my tab is on that image or not.

**Comment by rpearce** [comment]
@SaadAhmadSaddiqui Thanks for using this library and submitting an issue!

There is already buttons that are included with the library that zoom and unzoom the image. If you press tab, the zoom image button will appear.

For a screen reader, the button is announced after you encounter the image, and the button is labeled by "Zoom image:" plus the alternative text of the image, of there is any.

If I were to enable tabindex on the image, itself, the image would  now need an appropriate role (like button role), and it would lose its semantics as an image. We would then also need to provide button-related keyboard support, as well.

Since I do not see this library supporting this feature, and since an accessible alternative is already provided, I'm going to close this issue.

If you have more questions, please continue asking them here.

**Comment by SaadAhmadSaddiqui** [comment]
I actually want an option to give a tabIndex to the button itself. Problem I'm facing is that as I tab thru the tabIndexes that I have assigned, the focus after those goes to the places that are not assigned a tabIndex (in my case, then navbar) and after the navbar it comes to the zoom button where I can use enter to zoom the image.

What I require is that we can maybe pass a prop to zoom component something like `buttonTabIndex`. This way I can assign whatever index I require.

**Comment by rpearce** [comment]
I see, and thank you for explaining. 

While your tab order may work with pre-defined numbers, are you sure the order is maintained for screen readers?

From my experience working with accessibility, it is considered unwise to assign anything other than `0` or `-1` to a tabindex, for tabindex order will not be reflected with screen readers, and having these differ could create a  more difficult experience for people.

That said, I of course cannot know your situation.

If I open up the ability to assign a tabindex, then I go against what I believe to be a good practice, so I don't think this is something I'd like to support at the current time.

* * *

If this is absolutely what you need, you could try a `useEffect` or `componentDidUpdate` that queries for the button's data attribute and calls `btnEl.setAttribute('tabindex', 3)`. I don't know if this would work, but you could theoretically alter the HTML after a render and see what happens.

**Comment by SaadAhmadSaddiqui** [comment]
So I followed the pattern you mentioned and gave only 0 and -1 as the tab indexes and it works fine now. But obviously now the navbar is not accessible with tab anymore. I will try the method you mentioned as well and see if I can get better results. Thanks for the help Pearce!
