### ISSUE TITLE
Migrating to new mindset

### ISSUE THREAD

**Issue by sunknudsen** [rpearce/react-medium-image-zoom#392]
## Issue Type

- [ ] Bug report
- [ ] Feature request
- [x] Question / support request
- [ ] Other

## Description

Hey @rpearce,

Blessed you are still developing and maintaining this awesome package!

Working on integrating react-medium-image-zoom into new Next.js project and have a few questions.

One used to be able to configure background color and other aspects of `<Zoom>` using props which was very convenient to, for example, set background color based on theme variable.

It appears styling has moved to CSS which one can work around but perhaps doesn’t play well with CSS-in-JS.

I really like the zoom/unzoom button feature but one might want to disable feature (using prop?).

Would love to better understand new mindset and adjust… you know way better than I do.

**Comment by rpearce** [comment]
@sunknudsen Nice to hear from you!

## Styling

Regarding custom styling, I believe pretty much every css-in-js option provides an option to apply global styles and add styles that are local to the component. Here's one of the examples that has the zoom styles customized: https://rpearce.github.io/react-medium-image-zoom/?path=/story/img--custom-modal-styles

"But why `data-` selectors?" The CSS game for libraries is awful. Everybody has their own styling solution — some of which that dynamically add `<style>` tags at runtime are realizing that's a bad idea — and you run into these problems:

* If I use class names-only, what style do I use to represent state?
* Will my class names clash with the person's app or other libs?
* How will the styles be included in the project?
* If I accept style objects and `className`s, do I accept style objects and `className`s for _every element_? How do I know which ones are important to a user and which ones aren't?

In lieu of this, I'm convinced that component libraries should only provide a static stylesheet(s) that one can import _or_ copy and then change to suit one's style. Using `data-` selectors also means that the chance of class name collision is minimal, _and_ there is the benefit of easily being able to represent state; e.g., https://github.com/rpearce/react-medium-image-zoom/blob/16ebc24d38c28739f39c99b1f6bb616f7b0adb93/source/styles.css#LL74-L74C35

## Accessibility

I have done _a lot_ of accessibility work over the past 4 years, and lots of testing (including user testing) led to the realization that there needs to be an image and a button that does something.

If I make the image a button, then the image's semantics are lost. If I make the image clickable and focusable with a keyboard, then it needs to have a role that corresponds to an interactive element that can receive focus, and if I do that, the only thing that makes sense is `role="button"`, and now we lose the image's semantics again.

Having zoom/unzoom buttons on the page is something that is a necessary default to ensure users with assistive devices can adequately use this across the web.

There was a button in v4, too, but it covered the entire image. This then made it impossible to download images!

_That said_, since you can control the CSS, you could select these 2 selectors, https://github.com/rpearce/react-medium-image-zoom/blob/16ebc24d38c28739f39c99b1f6bb616f7b0adb93/source/styles.css#L8-L9, and set them to `display: none;`, and this would probably still work with a mouse, but that would likely create accessibility issues.

* * *

I welcome your questions and, of course, don't want to make extra work or pains for people. The state of the project right now, which is _pretty good, I think_ was arrived at over years of thinking about this. It doesn't make it right, but it's something.

**Comment by rpearce** [comment]
I'm doing a little cleanup, and I think I've answered everything here!
