### ISSUE TITLE
Using srcset on zoomImage does not work

### ISSUE THREAD

**Issue by jeremybini** [rpearce/react-medium-image-zoom#42]
I would like to be able to define `srcset` and `sizes` on the zoomImage prop, but adding either of these fields has no effect.

I think that any extra fields defined on zoomImage should be passed down to the img tag, and additionally `fetchZoomImage` would pass these fields into the `Image` element so that the onload function can respond to the proper image source. If this sounds reasonable I'm happy to put up a PR

**Comment by rpearce** [comment]
Indeed, `zoomImage` is not populating additional props it receives. If you want to take a stab at it, great!

Here is where the props get passed to zoomImage:
https://github.com/rpearce/react-medium-image-zoom/blob/master/src/react-medium-image-zoom.js#L143

And here is where it's getting rendered:
https://github.com/rpearce/react-medium-image-zoom/blob/master/src/react-medium-image-zoom.js#L275-L280

My initial thinking is that instead of spreading `{ ...this.props.zoomImage }` like this, these props should be set as a prop on their own that is passed to the zoom component, and then either a spread or something similar to it (there's some `src` stateful hackery going on in there) happens in the zoom component. <-- _Not my best written sentences, let me know if they don't make any sense._

If you decide you'd rather not put in the leg-work, I'm glad to help.

**Comment by jeremybini** [comment]
Yea, that makes sense to me - the same way ImageZoom has both `image` and `zoomImage` props. I'll be able to look into it today and let you know how things go.

**Comment by rpearce** [comment]
Closed by https://github.com/rpearce/react-medium-image-zoom/pull/43
