### ISSUE TITLE
Request: More options for being able to control the cursor and render it as the browser intends

### ISSUE THREAD

**Issue by davesierra** [rpearce/react-medium-image-zoom#449]
## Issue Type

- [ ] Bug report
- [X] Feature request
- [ ] Question / support request
- [ ] Other

## Description

While using the controlled component, I should to be able to choose the icon (which I believe exists now with IconZoom) but also make it the default browser `cursor: pointer` when selecting the image. 

In my specific case, the zooming function is handled by an offset button on the top right, and clicking on an image will select the image (for say a file browser), so hovering on the image should give the `cursor: pointer` css style. Currently, there seems to be no way to do this, even if I try to add the cursor styles to the actual image and the Uncontrolled component, it still is overwritten:

```
<ControlledZoom
                                isZoomed={zoomedImage && zoomedImage === imgUrl}
                                onZoomChange={handleZoomChange}
                                IconZoom="none"
                                className="cursor-pointer"
                              >
                                <img
                                  className="h-auto max-w-full rounded-lg cursor-pointer"
                                  src={imgUrl}
                                  alt=""
                                  onClick={() => selectImageHandler(imgUrl)}
                                />
                              </ControlledZoom>
```

Demo Video:

https://github.com/rpearce/react-medium-image-zoom/assets/867047/2a230548-0438-40d1-99dc-62c8f35cf54f

**Comment by davesierra** [comment]
Sometimes a simple fix is overlooked. For a temporary solution, I added a CSS style:

```
[data-rmiz-content="found"] img {
  cursor: pointer !important;
}
```

**Comment by rpearce** [comment]
Hi, and thanks for asking your question! 

Regarding `IconZoom`, that is for changing the zoom button icon. As [you can see here in the example story code](https://github.com/rpearce/react-medium-image-zoom/blob/ae91a61f60f4be1fea9c226d161ff547280dc932/stories/Img.stories.tsx#L414), you can pass a custom component (here, an inline function component).

As for customizing the browser `cursor`, CSS is the intended way to go, and you have two ways available to you to solve the problem (one of which you found but might be able to do without `!important`):

1. Instead of importing [the stylesheet](https://github.com/rpearce/react-medium-image-zoom/blob/main/source/styles.css), you could copy and paste it into your application and alter it to suit your needs (look for `cursor: ` lines). In the future, if you upgrade to a newer version, you'd just want to check that no CSS changes were included in the upgrade.
2. Override the styles—avoiding `!important`—by using the same selectors found in the CSS file and making sure that your app CSS is defined _after_ imported CSS.

* * *

Since I believe there are solutions here, and this isn't something I'm going to officially have an API for, I'm going to close this. Feel free to keep asking questions or follow up!
