### ISSUE TITLE
Enable configuration of dialog container 

### ISSUE THREAD

**Issue by membla** [rpearce/react-medium-image-zoom#466]
## Issue Type

- [ ] Bug report
- [X] Feature request
- [ ] Question / support request
- [ ] Other

## Description

When rendering React trees into other document contexts (through window.open, react-frame-component etc.) the component would need to specify what document to render the dialog in. An option to pass in a custom `getDialogContainer` could make it possible.

**Comment by rpearce** [comment]
@membla Could you share some example usage code of what you're thinking? I don't understand the problem scenarios yet.

**Comment by rpearce** [comment]
@membla If you are able to put together an example project of this not working, that would make it easier for me to understand the use-case and then provide a solution.

**Comment by membla** [comment]
Sure, an example https://codesandbox.io/p/sandbox/quiet-feather-fm7rkv

**Comment by rpearce** [comment]
I'm sorry for the very long delay on this. Based on the example, I don't think this is a feature I'm willing to support due to it not being a use case I've personally ever come across, and the potential additional lift for maintaining this behavior through all future releases. Thank you for raising it and showing me something new.
