### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by anburocky3** [rpearce/react-medium-image-zoom#639]
![image](https://github.com/user-attachments/assets/4d86643e-7743-4b89-9a62-5d16ff8fc683)

I have installed `"react-medium-image-zoom": "^5.2.7",`

```js
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'

// view
<Zoom>
  <img
   alt="That Wanaka Tree, New Zealand by Laura Smetsers"
   src={`https://ui-avatars.com/api/?name=${user.name}&background=random&size=128`}
  width="500"  />
</Zoom>
```

**Comment by rpearce** [comment]
@anburocky3 Can you please provide more information about how to reproduce this? What tools are being used? If the problem is with this library, an example project that demonstrates the problem would be perfect.

However, first, have you tried the solutions in this Stack Overflow? https://stackoverflow.com/questions/69300341/typeerror-failed-to-fetch-dynamically-imported-module-on-vue-vite-vanilla-set

**Comment by anburocky3** [comment]
Sorry i was dumb. restarted the dev-server fixed the issue. Will close it. And wonderful work by you. Thanks.
